FROM python:3.12-bookworm

WORKDIR /app

COPY requirements /app/requirements

RUN pip install --no-cache-dir -r requirements.txt

COPY . /app

CMD ["uvicorn", "spaceship.app:app", "--host", "0.0.0.0", "--port", "8080"]

