FROM golang:1.22-bookworm AS builder
WORKDIR /build
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o main .

FROM gcr.io/distroless/static-debian12
WORKDIR /app
COPY --from=builder /build/main /app/main
COPY --from=builder /build/templates /app/templates

CMD ["./main", "serve"]

